# -*- coding: utf-8 -*-
"""Untitled24 (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KNEGrHxxpq7Ei3uiL1KE7HoqvBDIsan4
"""

!pip install streamlit pyngrok

from google.colab import drive
drive.mount('/content/drive')

import zipfile, os

zip_path = '/content/drive/MyDrive/archive.zip'
extract_path = '/content/images_folder/'
os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print(" تم فك الضغط!")

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd

dataset_path = "/content/images_folder/train"
categories = ["Normal", "OSCC"]

data = []
for category in categories:
    folder_path = os.path.join(dataset_path, category)
    label = category
    for file_name in os.listdir(folder_path):
        if file_name.endswith(('.png', '.jpg', '.jpeg')):
            file_path = os.path.join(folder_path, file_name)
            data.append([file_path, label])

df = pd.DataFrame(data, columns=["file_path", "label"])
df.head()

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='label', data=df)
plt.title("Number of images for each categoryة")
plt.show()

df['label'].value_counts(normalize=True).plot(kind='pie', autopct='%1.1f%%')
plt.title("Percentage of images per category")
plt.ylabel("")
plt.show()

import cv2
num_samples = 5
fig, axes = plt.subplots(2, num_samples, figsize=(15, 6))

for i, category in enumerate(df['label'].unique()):
    imgs = df[df['label'] == category].head(num_samples)
    for j, path in enumerate(imgs['file_path']):
        img = cv2.imread(path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        axes[i, j].imshow(img)
        axes[i, j].axis('off')
        if j == 0:
            axes[i, j].set_ylabel(category, fontsize=14)

plt.tight_layout()
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

train_df, temp_df = train_test_split(df, test_size=0.2, stratify=df['label'], random_state=42)
valid_df, test_df = train_test_split(temp_df, test_size=0.5, stratify=temp_df['label'], random_state=42)

label_encoder = LabelEncoder()
train_df['Encoded_Label'] = label_encoder.fit_transform(train_df['label'])
valid_df['Encoded_Label'] = label_encoder.transform(valid_df['label'])
test_df['Encoded_Label'] = label_encoder.transform(test_df['label'])

print("Category coding:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

from tensorflow.keras.preprocessing.image import ImageDataGenerator

#  تحويل القيم في عمود التصنيفات إلى نصوص (لـ class_mode='binary')
train_df['Encoded_Label'] = train_df['Encoded_Label'].astype(str)
valid_df['Encoded_Label'] = valid_df['Encoded_Label'].astype(str)
test_df['Encoded_Label']  = test_df['Encoded_Label'].astype(str)

# إعداد المولدات
batch_size = 16
img_size = (299, 299)
channels = 3
img_shape = (img_size[0], img_size[1], channels)

tr_gen = ImageDataGenerator(rescale=1./255)
ts_gen = ImageDataGenerator(rescale=1./255)

# مولد بيانات التدريب
train_gen_new = tr_gen.flow_from_dataframe(
    train_df,
    x_col='file_path',
    y_col='Encoded_Label',
    target_size=img_size,
    class_mode='binary',
    color_mode='rgb',
    shuffle=True,
    batch_size=batch_size
)

valid_gen_new = ts_gen.flow_from_dataframe(
    valid_df,
    x_col='file_path',
    y_col='Encoded_Label',
    target_size=img_size,
    class_mode='binary',
    color_mode='rgb',
    shuffle=True,
    batch_size=batch_size
)

test_gen_new = ts_gen.flow_from_dataframe(
    test_df,
    x_col='file_path',
    y_col='Encoded_Label',
    target_size=img_size,
    class_mode='binary',
    color_mode='rgb',
    shuffle=False,
    batch_size=batch_size
)

from tensorflow.keras.applications import InceptionV3
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

base_model = InceptionV3(weights='imagenet', include_top=False, input_shape=(299, 299, 3))
base_model.trainable = False

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

history = model.fit(train_gen_new, validation_data=valid_gen_new, epochs=10, callbacks=[early_stopping])

plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train')
plt.plot(history.history['val_accuracy'], label='Validation')
plt.title("accuracy")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train')
plt.plot(history.history['val_loss'], label='Validation')
plt.title("loss")
plt.legend()

plt.tight_layout()
plt.show()

from sklearn.metrics import confusion_matrix, classification_report, recall_score
import numpy as np

preds = model.predict(test_gen_new)
y_pred = (preds > 0.5).astype(int).ravel()

y_true = test_df['Encoded_Label'].astype(int).values

print(" Recall:", recall_score(y_true, y_pred))

print("\n Confusion Matrix:")
print(confusion_matrix(y_true, y_pred))

print("\n Classification Report:")
print(classification_report(y_true, y_pred, target_names=label_encoder.classes_))

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=False,
            xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# التنبؤ بالاحتمالات
y_probs = model.predict(test_gen_new).ravel()

# حساب TPR و FPR
fpr, tpr, thresholds = roc_curve(y_true, y_probs)
roc_auc = auc(fpr, tpr)

# رسم المنحنى
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

#سم منحنى Precision-Recall Curve
from sklearn.metrics import precision_recall_curve, average_precision_score
import matplotlib.pyplot as plt

# التنبؤ بالاحتمالات
y_probs = model.predict(test_gen_new).ravel()

# حساب Precision و Recall
precision, recall, thresholds = precision_recall_curve(y_true, y_probs)
avg_precision = average_precision_score(y_true, y_probs)

# رسم المنحنى
plt.figure(figsize=(8, 6))
plt.plot(recall, precision, color='blue', lw=2, label=f'Avg Precision = {avg_precision:.2f}')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve')
plt.legend(loc='lower left')
plt.grid(True)
plt.show()

# تحديد المسار داخل Google Drive
model_save_path = "/content/drive/MyDrive/inceptionv3_model.h5"

# حفظ النموذج
model.save(model_save_path)

print(f" تم حفظ النموذج في: {model_save_path}")

from tensorflow.keras.models import load_model

# تحميل النموذج من Google Drive
loaded_model = load_model("/content/drive/MyDrive/inceptionv3_model.h5")

print(" تم تحميل النموذج بنجاح!")

report = classification_report(y_true, y_pred, target_names=label_encoder.classes_)

with open("/content/drive/MyDrive/classification_report.txt", "w") as f:
    f.write(report)

print(" تم حفظ تقرير التصنيف في classification_report.txt")
# 3. حفظ نتائج التقييم (مصفوفة الالتباس + التقرير النصي)
# 3.1 حفظ تقرير التصنيف كنص

import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model


def predict_image(image_path):
    # تحميل الصورة وتعديل الحجم
    img = cv2.imread(image_path)
    img_resized = cv2.resize(img, (299, 299))
    img_rgb = cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB)

    # تجهيز الصورة للنموذج
    img_array = img_rgb / 255.0
    img_array = np.expand_dims(img_array, axis=0)  # الشكل (1, 299, 299, 3)

    # التنبؤ
    prediction = model.predict(img_array)[0][0]

    # تحديد الفئة
    if prediction > 0.5:
        result = "OSCC"
        color = "red"
    else:
        result = "Normal"
        color = "green"

    # عرض الصورة مع النتيجة
    plt.figure(figsize=(5, 5))
    plt.imshow(img_rgb)
    plt.title(f"{result} - ({prediction:.2f})", fontsize=14, color=color)
    plt.axis('off')
    plt.show()

predict_image('/content/images_folder/test/Normal/Normal_400x_89.jpg')

predict_image('/content/images_folder/test/OSCC/OSCC_100x_113.jpg')

predict_image('/content/images_folder/test/Normal/Normal_100x_12.jpg')

# ================== AlexNet Model ==================

print("\n🚀 Starting AlexNet Model...\n")

from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# ⚠️ حجم خاص بـ AlexNet
alex_img_size = (227, 227)
batch_size = 16

# 🔄 Generators خاصة بـ AlexNet (لا نغير القديمة)
alex_train_gen = ImageDataGenerator(rescale=1./255)
alex_valid_gen = ImageDataGenerator(rescale=1./255)
alex_test_gen  = ImageDataGenerator(rescale=1./255)

train_gen_alex = alex_train_gen.flow_from_dataframe(
    train_df,
    x_col='file_path',
    y_col='Encoded_Label',
    target_size=alex_img_size,
    class_mode='binary',
    batch_size=batch_size
)

valid_gen_alex = alex_valid_gen.flow_from_dataframe(
    valid_df,
    x_col='file_path',
    y_col='Encoded_Label',
    target_size=alex_img_size,
    class_mode='binary',
    batch_size=batch_size
)

test_gen_alex = alex_test_gen.flow_from_dataframe(
    test_df,
    x_col='file_path',
    y_col='Encoded_Label',
    target_size=alex_img_size,
    class_mode='binary',
    shuffle=False,
    batch_size=batch_size
)

# 🧠 بناء AlexNet
def build_alexnet():
    model = models.Sequential()

    model.add(layers.Conv2D(96, (11,11), strides=4, activation='relu', input_shape=(227,227,3)))
    model.add(layers.MaxPooling2D((3,3), strides=2))

    model.add(layers.Conv2D(256, (5,5), padding='same', activation='relu'))
    model.add(layers.MaxPooling2D((3,3), strides=2))

    model.add(layers.Conv2D(384, (3,3), padding='same', activation='relu'))
    model.add(layers.Conv2D(384, (3,3), padding='same', activation='relu'))
    model.add(layers.Conv2D(256, (3,3), padding='same', activation='relu'))
    model.add(layers.MaxPooling2D((3,3), strides=2))

    model.add(layers.Flatten())

    model.add(layers.Dense(4096, activation='relu'))
    model.add(layers.Dropout(0.5))

    model.add(layers.Dense(4096, activation='relu'))
    model.add(layers.Dropout(0.5))

    model.add(layers.Dense(1, activation='sigmoid'))

    return model

alex_model = build_alexnet()

alex_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 🚀 التدريب
history_alex = alex_model.fit(
    train_gen_alex,
    validation_data=valid_gen_alex,
    epochs=10
)

# 📊 رسم النتائج
import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.plot(history_alex.history['accuracy'], label='Train')
plt.plot(history_alex.history['val_accuracy'], label='Validation')
plt.title("AlexNet Accuracy")
plt.legend()

plt.subplot(1,2,2)
plt.plot(history_alex.history['loss'], label='Train')
plt.plot(history_alex.history['val_loss'], label='Validation')
plt.title("AlexNet Loss")
plt.legend()

plt.show()

# 🧪 التقييم
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

preds_alex = alex_model.predict(test_gen_alex)
y_pred_alex = (preds_alex > 0.5).astype(int).ravel()
y_true_alex = test_df['Encoded_Label'].astype(int).values

print("\n📊 AlexNet Results:")
print("Accuracy:", accuracy_score(y_true_alex, y_pred_alex))

print("\nConfusion Matrix:")
print(confusion_matrix(y_true_alex, y_pred_alex))

print("\nClassification Report:")
print(classification_report(y_true_alex, y_pred_alex, target_names=label_encoder.classes_))

# 💾 حفظ النموذج
alex_model.save("/content/drive/MyDrive/alexnet_model.h5")

print("\n✅ AlexNet model saved successfully!")